
name: Package and Deploy
on: [push]
jobs:
  package:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: asdfasdf
          POSTGRES_DB: eil_db_1
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 18
        uses: actions/setup-java@v1
        with:
          java-version: 1.18
      - name: Gradle Build
        run: ./gradlew build --stacktrace --info
        env:
          HOSTNAME: localhost
          JWT_SECRET: asdfasdf
          AWS_ACCESS_KEY_ID: asdf
          AWS_SECRET_ACCESS_KEY: asdf
          DB_DOMAIN: localhost
          DB_USERNAME: postgres
          DB_DATABASE: eil_db_1
          DB_PASSWORD: asdfasdf
          S3_URL_PREFIX: asdf
          KAFKA_BOOTSTRAP: "localhost:9092"
      - name: Gradle Package BootJar
        run: ./gradle bootJar